# This workflow will check our code for having a proper format, as well as the commit message to meet the expected ones

name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-commit:
    runs-on: ubuntu-latest
    name: "Lint commit message"
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install commitizen
        run: |
          python -m pip install --upgrade pip
          python -m pip install commitizen

      - name: Check commit message
        run: cz check --rev-range HEAD
